eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:8761/eureka/
 instance:
  hostname: localhost  
 
logging:
 file: logs/application-debug.log
 pattern:
  console: "%d %-5level %logger : %msg%n"
  file: "%d %-5level [%thread] %logger : %msg%n"
 level:
  root: INFO
  org.springframework.web: INFO
  com.spring.micro: INFO
  org.hibernate: INFO

microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookorder  
 
  
